tap 'homebrew/cask-fonts'

brew 'asdf'
brew 'coreutils'
brew 'curl'
brew 'fzf'
brew 'git-delta'
brew 'gnupg'
brew 'httpie'
brew 'jq'
brew 'neovim'
brew 'pinentry-mac'
brew 'ripgrep'
brew 'tmux'
brew 'tree'
brew 'tree-sitter'
brew 'wget'

cask 'docker'
cask 'docker-desktop'
cask 'font-fira-code-nerd-font'
cask 'font-meslo-for-powerlevel10k'
cask 'font-liberation'
cask 'alacritty'
cask 'wezterm'
cask 'proton-drive'
cask 'rar'
