# Make sure true color works properly
set-option -sa terminal-overrides ",xterm*:Tc"

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# Change prefix so use same as nvim
unbind C-b
set-option -g prefix C-\\
bind C-a send-prefix

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# Alt+arrow keys to quickly switch between panes without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Start windows and panes at index 1 instead of 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set -g renumber-windows on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-yank'

set -g @catppuccin_flavour 'frappe'

# set vi-mode
set-window-option -g mode-keys vi
# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Make sure clear works
bind C-l send-keys 'C-l'

# move pane to other window
bind-key < command-prompt -p "join pane from:" "join-pane -s '%%'"
bind-key > command-prompt -p "send pane to:" "join-pane -t '%%'"

# Set title bar of terminal
set -g set-titles on

run "$XDG_CONFIG_HOME/tmux/plugins/tpm/tpm"

# Set window notifications
# setw -g monitor-activity on
# set -g visual-activity on

# hide and show panes
# bind ! break-pane -d -n _hidden_pane
# bind @ join-pane -s $.0

