# Set colour mode
set -g default-terminal 'xterm-256color'
set-option -ga terminal-overrides ',xterm-256color:Tc'

# increase scrollback buffer size
set -g history-limit 50000

# Set title bar of terminal
set -g set-titles on

# source $XDG_CONFIG_HOME/tmux/tmux_tokyonight_storm.tmux
source $XDG_CONFIG_HOME/tmux/tokyonight.statusline
source $XDG_CONFIG_HOME/tmux/vim

# Change prefix to \, same as leader in vim
unbind C-b ; set-option -g prefix C-\\

set-option -sg escape-time 10

# Make sure clear works
bind C-l send-keys 'C-l'

# Reload config with c-r
bind r source-file ~/.config/tmux/tmux.conf

bind-key k confirm kill-window

# Count sessions start at 1
set -g base-index 1

# renumber windows sequentially after closing any of them
set -g renumber-windows on

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# Set window notifications
setw -g monitor-activity on
set -g visual-activity on

# easier and faster switching between next/prev window
bind C-p previous-window
bind C-n next-window

# hide and show panes
bind ! break-pane -d -n _hidden_pane
bind @ join-pane -s $.0
