import = ["~/.config/alacritty/catppuccin/catppuccin-macchiato.toml"]
live_config_reload = true

[font]
size = 14
normal.family = "MesloLGS NF"
italic.family = "MesloLGS NF"
bold.family = "MesloLGS NF"
bold_italic.family = "MesloLGS NF"

[window]
dynamic_title = true
option_as_alt = "OnlyLeft"
